-- Gerado por Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   em:        2020-08-26 21:43:17 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g


DROP TABLE t_bairro CASCADE CONSTRAINTS;

DROP TABLE t_cidade CASCADE CONSTRAINTS;

DROP TABLE t_dep_func CASCADE CONSTRAINTS;

DROP TABLE t_endereco CASCADE CONSTRAINTS;

DROP TABLE t_estado CASCADE CONSTRAINTS;

DROP TABLE t_fone_usuario CASCADE CONSTRAINTS;

DROP TABLE t_func CASCADE CONSTRAINTS;

DROP TABLE t_func_end CASCADE CONSTRAINTS;

DROP TABLE t_func_projetos CASCADE CONSTRAINTS;

DROP TABLE t_operadora CASCADE CONSTRAINTS;

DROP TABLE t_projetos CASCADE CONSTRAINTS;

DROP TABLE t_tipo_end CASCADE CONSTRAINTS;

DROP TABLE t_tipo_fone CASCADE CONSTRAINTS;

DROP TABLE t_tipo_logradouro CASCADE CONSTRAINTS;

